#!/bin/sh


SKEL_REPO="https://github.com/freenit-framework/frontend-startkit"
PROJECT_NAME="${1}"

if [ -z "${PROJECT_NAME}" ]; then
  echo "Usage: $0 <project name>" >&2
  exit 1
fi

if [ -e "${PROJECT_NAME}" ]; then
  echo "Directory ${PROJECT_NAME} already exists!" >&2
  exit 1
fi

git clone "${SKEL_REPO}" "${PROJECT_NAME}"
rm -rf "${PROJECT_NAME}/.git" "${PROJECT_NAME}/create-freenit"
echo "app_name=\"${PROJECT_NAME}\"" >"${PROJECT_NAME}/name.ini"
